package com.truevalue.dreamappeal.utils

object Noti_Param {

    val PROFILE_FOLLOW = "404"
    val PROFILE_LIKE = "504"
    val PROFILE_COMMENT = "604"
    val PROFILE_COMMENT_LIKE = "704"
    val ACTION_LIKE = "510"
    val LIFE_LIKE = "511"
    val IDEA_LIKE = "512"
    val ACHIEVEMENT_LIKE = "524"
    val ACTION_COMMENT = "610"
    val LIFE_COMMENT = "611"
    val IDEA_COMMENT = "612"
    val ACHIEVEMENT_COMMENT = "624"
    val ACTION_RE_COMMENT = "310"
    val LIFE_RE_COMMENT = "311"
    val IDEA_RE_COMMENT = "312"
    val PROFILE_RE_COMMENT ="313"
    val ACHIEVEMENT_RE_COMMENT = "324"
    val ACTION_COMMENT_LIKE = "710"
    val LIFE_COMMENT_LIKE = "711"
    val IDEA_COMMENT_LIKE = "712"
    val ACHIEVEMET_COMMENT_LIKE = "724"
    val CONCERN_COMMENT_ADDED = "630"
    val CONCERN_VOTED = "631"
    val RE_CONCERN_ADOPTED = "632"
    val RE_CONCERN_VOTED = "633"
    val NOTICES = "101"
    val BEST_PROFILE = "204"
    val BEST_ACTION = "214"
    val BEST_IDEA = "224"
    val PROFILE_VALUE_STYLE_JOB = "000"
    val PROFILE_DESCRIPTION = "001"
    val PROFILE_MERIT_MOTIVE = "002"
    val PROFILE_ACHIEVEMENT_POST = "003"
    val COMPLETE_PROFILE_OBJECT = "004"
    val ABILITY = "005"
    val OPPORTUNITY = "006"
    val PROFILE_OBJECT = "007"
    val ADD_ACTION = "010"
    val ADD_LIFE = "011"
    val ADD_IDEA = "012"
}