package com.truevalue.dreamappeal.bean

data class BeanDreamPresent(var idx : Int,
                            var user_idx : Int,
                            var profile_order : Int,
                            var exp : Int,
                            var point : Int,
                            var image : String?,
                            var value_style : String,
                            var job : String,
                            var description : String,
                            var meritNmotive : String,
                            var profile_init : Int,
                            var action_post_init : Int,
                            var achievement_post_count : Int,
                            var action_post_count : Int,
                            var name : String,
                            var comment_count : Int,
                            var like_count : Int,
                            var status : Boolean,
                            var level : Int,
                            var descriptions: ArrayList<String>)